---
trigger:
  branches:
    include:
    - 'main'
  paths:
    include:
    - environments/staging
    - modules

pr: none

pool: 'CM PreProd Pool'

jobs:
  - template: templates/terragrunt_job.yml
    parameters:
      environment: staging
      module: applications
      subscription: "Azure Pipeline: Case Management - Pre-Prod" #service principal
      runApply: true
      variableGroupName: 'cm-infra-vars-staging'

  - template: templates/terragrunt_job.yml
    parameters:
      environment: staging
      module: base
      subscription: "Azure Pipeline: Case Management - Pre-Prod" #service principal
      runApply: true
