---
trigger:
  branches:
    include:
    - 'main'
  paths:
    include:
    - environments/dev
    - modules

pr: none

pool: 'CM PreProd Pool'

jobs:
  - template: templates/terragrunt_apply.yml
    parameters:
      environment: dev
      module: applications
      subscription: "Azure Pipeline: Case Management - Pre-Prod" #service principal
      backend_storage_resource_group: "rg-cm-devops-preprod"
      backend_storage_account_name: "sacmtfstatedev"
      application_name: "applications"

  - template: templates/terragrunt_apply.yml
    parameters:
      environment: dev
      module: base
      subscription: "Azure Pipeline: Case Management - Pre-Prod" #service principal
      backend_storage_resource_group: "rg-cm-devops-preprod"
      backend_storage_account_name: "sacmtfstatedev"
      application_name: "base"
